[package]
name = "av-denoise-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core kernels and types for av-denoise (Do not use directly)"
categories = ["multimedia::video"]
keywords = ["cubecl", "denoise", "gpu"]
readme = "README.md"
exclude = [
    "scripts/",
    ".idea/",
    "cubecl.toml",
    "docker/",
    ".github/",
    "Justfile"
]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = "1"
thiserror = "2"
tracing = "0.1"
strum_macros = "0.28"
strum = "0.28"
bon = "3"
etcetera = "0.11"

cubecl = { version = "0.10", features = ["std"] }

[dev-dependencies]
futures = "0.3"
clap = { version = "4", features = ["derive"] }
tempfile = "3"

[features]
vulkan = ["cubecl/vulkan"]
metal = ["cubecl/metal"]
cuda = ["cubecl/cuda"]
rocm = ["cubecl/hip"]
default = ["vulkan"]

[[bench]]
name = "nlmeans"
harness = false

[[bench]]
name = "bench_kernels"
harness = false

[[bench]]
name = "denoise"
harness = false

[[bench]]
name = "motion"
harness = false

[[bench]]
name = "convert"
harness = false

[[bench]]
name = "nl4d_ablation"
harness = false

[[bench]]
name = "reseed"
harness = false

[[bench]]
name = "mc_accuracy"
harness = false
